/**
 * Web implementation of `plugin-llama-cpp`.
 *
 * There is no llama.cpp in a browser tab, and pretending otherwise would be
 * dishonest instrumentation. Instead this shim does two real things and one
 * clearly-labelled fake one:
 *
 *  1. If the browser exposes an on-device model through the Prompt API
 *     (`LanguageModel`, Chrome 138+), generation is genuinely local and the
 *     reported compute backend says so.
 *  2. Token counts use a deterministic byte-pair-ish estimate so the context
 *     meter and benchmark maths behave the same as on device.
 *  3. Otherwise it streams a synthesised response and reports
 *     `simulated: true`, which the UI surfaces as a visible banner. Every
 *     screen stays exercisable in `npm run dev` without a 2 GB download.
 */

import { WebPlugin } from '@capacitor/core';
import type {
  BenchmarkOptions,
  BenchmarkResult,
  DeviceCapabilities,
  GenerateOptions,
  GenerateResult,
  LlamaCppPlugin,
  LoadOptions,
  LoadResult,
  ThermalState,
} from './definitions';

interface PromptSession {
  promptStreaming(input: string): AsyncIterable<string>;
  destroy(): void;
}

interface PromptApi {
  availability(): Promise<'unavailable' | 'downloadable' | 'downloading' | 'available'>;
  create(options?: { temperature?: number; topK?: number }): Promise<PromptSession>;
}

function getPromptApi(): PromptApi | null {
  const api = (globalThis as { LanguageModel?: PromptApi }).LanguageModel;
  return api && typeof api.create === 'function' ? api : null;
}

/** Rough token estimate: ~3.6 chars/token for English prose. */
export function estimateTokens(text: string): number {
  if (!text) return 0;
  return Math.max(1, Math.round(text.length / 3.6));
}

interface LoadedModel {
  handle: string;
  path: string;
  contextLength: number;
  supportsVision: boolean;
  session: PromptSession | null;
}

const LOREM_VOCAB = [
  'The model runs entirely on this device.',
  'Nothing in this conversation has left your phone.',
  'Weights are memory-mapped from app-private storage.',
  'Prompt processing is the expensive part; decode is steady after that.',
  'Quantisation trades a little accuracy for a lot of memory.',
  'A draft model proposes tokens and the large model verifies them.',
  'When the device gets warm, throughput drops before anything else does.',
];

export class LlamaCppWeb extends WebPlugin implements LlamaCppPlugin {
  #models = new Map<string, LoadedModel>();
  #cancelled = new Set<string>();
  #counter = 0;

  async getCapabilities(): Promise<DeviceCapabilities> {
    const memory = (navigator as { deviceMemory?: number }).deviceMemory ?? 8;
    const promptApi = getPromptApi();
    const hasWebGpu = 'gpu' in navigator;

    // The Prompt API can be present but unusable — the model may still be
    // downloading, or unavailable on this channel. Reporting "not simulated"
    // on presence alone would tell the user a real model is running when the
    // shim is what actually answers.
    const promptReady =
      promptApi !== null &&
      (await promptApi.availability().catch(() => 'unavailable')) === 'available';

    const backends: DeviceCapabilities['backends'] = ['cpu'];
    if (hasWebGpu) backends.push('gpu-vulkan');

    return {
      totalMemory: memory * 1024 ** 3,
      availableMemory: Math.round(memory * 0.55) * 1024 ** 3,
      backends,
      preferredBackend: hasWebGpu ? 'gpu-vulkan' : 'cpu',
      cpuCores: navigator.hardwareConcurrency ?? 4,
      chipset: promptReady ? 'Browser (Prompt API)' : 'Browser (development shim)',
      simulated: !promptReady,
      engineVersion: promptReady ? 'chrome-prompt-api' : 'chatterang-dev-shim',
    };
  }

  async getThermalState(): Promise<ThermalState> {
    return { level: 0.12, state: 'nominal', throttled: false };
  }

  async load(options: LoadOptions): Promise<LoadResult> {
    const started = performance.now();
    const handle = `web_${++this.#counter}`;
    const warnings: string[] = [];

    let session: PromptSession | null = null;
    const promptApi = getPromptApi();
    if (promptApi) {
      const availability = await promptApi.availability().catch(() => 'unavailable' as const);
      if (availability === 'available') {
        session = await promptApi.create().catch(() => null);
      } else if (availability === 'downloadable' || availability === 'downloading') {
        warnings.push('The browser model is still downloading; using the development shim.');
      }
    }

    if (!session) {
      warnings.push(
        'Running the browser development shim. Responses are synthesised, not generated by a model.',
      );
    }

    this.#models.set(handle, {
      handle,
      path: options.modelPath,
      contextLength: options.contextLength ?? 4096,
      supportsVision: Boolean(options.mmprojPath),
      session,
    });

    return {
      handle,
      backend: options.backend ?? ('gpu' in navigator ? 'gpu-vulkan' : 'cpu'),
      contextLength: options.contextLength ?? 4096,
      loadMs: Math.round(performance.now() - started),
      warnings,
      supportsVision: Boolean(options.mmprojPath),
      chatTemplate: options.chatTemplate ?? 'chatml',
    };
  }

  async unload({ handle }: { handle: string }): Promise<void> {
    this.#models.get(handle)?.session?.destroy();
    this.#models.delete(handle);
  }

  async listLoaded(): Promise<{ handles: string[] }> {
    return { handles: [...this.#models.keys()] };
  }

  async generate(options: GenerateOptions): Promise<GenerateResult> {
    const model = this.#models.get(options.handle);
    if (!model) throw new Error(`No model loaded for handle ${options.handle}`);

    this.#cancelled.delete(options.requestId);
    const started = performance.now();
    let firstTokenAt = 0;
    let index = 0;
    let text = '';

    const emit = (token: string): void => {
      if (index === 0) firstTokenAt = performance.now();
      text += token;
      this.notifyListeners('llamaToken', { requestId: options.requestId, token, index });
      index += 1;
    };

    let stopReason: GenerateResult['stopReason'] = 'stop';

    try {
      if (model.session) {
        for await (const chunk of model.session.promptStreaming(options.prompt)) {
          if (this.#cancelled.has(options.requestId)) {
            stopReason = 'cancelled';
            break;
          }
          emit(chunk);
        }
      } else {
        for await (const token of this.#synthesise(options)) {
          if (this.#cancelled.has(options.requestId)) {
            stopReason = 'cancelled';
            break;
          }
          emit(token);
          if (estimateTokens(text) >= (options.sampler?.maxTokens ?? 1024)) {
            stopReason = 'length';
            break;
          }
        }
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const result = this.#result(options, text, started, firstTokenAt, 'error');
      this.notifyListeners('llamaEnd', { ...result, error: message });
      throw error;
    }

    const result = this.#result(options, text, started, firstTokenAt, stopReason);
    this.notifyListeners('llamaEnd', result);
    return result;
  }

  #result(
    options: GenerateOptions,
    text: string,
    started: number,
    firstTokenAt: number,
    stopReason: GenerateResult['stopReason'],
  ): GenerateResult {
    const totalMs = Math.max(1, Math.round(performance.now() - started));
    const completionTokens = estimateTokens(text);
    return {
      requestId: options.requestId,
      text,
      promptTokens: estimateTokens(options.prompt),
      // The shim has no KV cache. Reporting a plausible-looking saving would
      // make a real regression invisible in development.
      cachedTokens: 0,
      completionTokens,
      ttftMs: firstTokenAt ? Math.round(firstTokenAt - started) : totalMs,
      totalMs,
      tokensPerSecond: Number(((completionTokens / totalMs) * 1000).toFixed(2)),
      stopReason,
      peakMemoryBytes: 512 * 1024 * 1024,
    };
  }

  /**
   * Deterministic pseudo-generation. Seeded from the prompt so the same
   * question yields the same answer — useful when testing the UI, and
   * unmistakably not a real model.
   */
  async *#synthesise(options: GenerateOptions): AsyncGenerator<string> {
    const seed = [...options.prompt].reduce((acc, ch) => (acc * 31 + ch.charCodeAt(0)) >>> 0, 7);
    let cursor = seed;
    const next = (): number => (cursor = (cursor * 1664525 + 1013904223) >>> 0);

    // Recover the user's own words from the rendered prompt: strip template
    // control tokens, then take the last non-empty line.
    const question =
      options.prompt
        .replace(/<\|[^|]*\|>/g, '\n')
        .replace(/<\/?(?:start_of_turn|end_of_turn|s|INST)[^>]*>/gi, '\n')
        .replace(/\[\/?INST\]/gi, '\n')
        .replace(/^(?:system|user|assistant|model)\s*$/gim, '')
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .at(-1) ?? '';
    const lines = [
      `Running on the development shim, so this text is synthesised rather than generated.`,
      ``,
      question.length > 12
        ? `You asked about: ${question.replace(/^\w+:\s*/, '').slice(0, 120)}`
        : `Send a longer prompt to see how the streaming surface behaves.`,
      ``,
    ];

    const sentenceCount = 3 + (next() % 3);
    for (let i = 0; i < sentenceCount; i += 1) {
      lines.push(LOREM_VOCAB[next() % LOREM_VOCAB.length] ?? '');
    }

    if (options.images?.length) {
      lines.push(
        ``,
        `Received ${options.images.length} image${options.images.length === 1 ? '' : 's'}; on device these route through llama.cpp's mtmd projector.`,
      );
    }

    const body = lines.join('\n');
    const chunks = body.match(/\S+\s*|\n/g) ?? [body];
    for (const chunk of chunks) {
      await new Promise((resolve) => setTimeout(resolve, 14 + (next() % 26)));
      yield chunk;
    }
  }

  async cancel({ requestId }: { requestId: string }): Promise<void> {
    this.#cancelled.add(requestId);
  }

  async tokenize({ text }: { handle: string; text: string }): Promise<{ tokens: number[] }> {
    const count = estimateTokens(text);
    return { tokens: Array.from({ length: count }, (_, i) => i) };
  }

  async countTokens({ text }: { handle: string; text: string }): Promise<{ count: number }> {
    return { count: estimateTokens(text) };
  }

  async benchmark(options: BenchmarkOptions): Promise<BenchmarkResult> {
    const repetitions = options.repetitions ?? 3;
    const samples: number[] = [];
    const before = await this.getThermalState();

    for (let i = 0; i < repetitions; i += 1) {
      const started = performance.now();
      // Do measurable work so the number reflects this machine rather than a
      // hard-coded constant.
      let checksum = 0;
      for (let j = 0; j < 2_000_000; j += 1) checksum = (checksum + Math.sqrt(j)) % 100_000;
      const elapsed = Math.max(1, performance.now() - started);
      samples.push(Number((((options.generateTokens ?? 128) / elapsed) * 1000).toFixed(2)));
    }

    const mean = samples.reduce((a, b) => a + b, 0) / samples.length;
    return {
      promptTokensPerSecond: Number((mean * 6.5).toFixed(2)),
      generateTokensPerSecond: Number(mean.toFixed(2)),
      peakMemoryBytes: 512 * 1024 * 1024,
      thermalBefore: before,
      thermalAfter: await this.getThermalState(),
      backend: 'cpu',
      repetitions,
      samples,
    };
  }
}
