#!/usr/bin/env bash
#
# Drive `prove-ios.js` on a booted iOS simulator and print what it measured.
#
#   ./native/plugin-llama-cpp/tools/prove-ios.sh /abs/path/to/model.gguf
#
# Builds the web app, appends the harness to the built `dist/index.html`,
# `cap sync`s, builds and installs the app, launches it with the console
# attached, and pulls the `[PROVE]` lines out of the log.
#
# The harness touches only `dist/`, which is gitignored and regenerated by
# `npm run build:web`, so nothing it does survives into a normal build.
#
# Exit status is the harness's: non-zero if any step reported `ok: false`, if
# the run never reached `done`, or if any generate emitted other than exactly
# one `llamaEnd`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
MODEL="${1:?usage: prove-ios.sh /abs/path/to/model.gguf [prompt]}"
# The turn markers this model actually uses, read out of its own GGUF chat
# template (`tokenizer.chat_template`): gemma4 opens with `<|turn>role` and
# closes with `<turn|>`, which is NOT the `<start_of_turn>` / `<end_of_turn>`
# pair `src/ai/prompt.ts`'s `gemma` template emits. WRONG_PROMPT is that older
# pair, kept deliberately so one run shows both and the difference is visible.
PROMPT="${2:-${PROVE_PROMPT:-<|turn>user
What is the capital city of Australia? Answer in one word.<turn|>
<|turn>model
}}"
CREATIVE_PROMPT="${PROVE_CREATIVE_PROMPT:-<|turn>user
Invent one strange sentence about the sea. Just the sentence.<turn|>
<|turn>model
}"
WRONG_PROMPT="${PROVE_WRONG_PROMPT:-<start_of_turn>user
What is the capital city of Australia? Answer in one word.<end_of_turn>
<start_of_turn>model
}"
# Overridable for the same reason as in `prove-android.sh`: the family belongs
# to the model you pass in. Keeping the two scripts' knobs identically named is
# what makes a cross-platform tokenizer diff a matter of running both with the
# same environment.
TEMPLATE_NAME="${PROVE_TEMPLATE_NAME:-gemma4}"
TEMPLATE_MARKERS="${PROVE_TEMPLATE_MARKERS:-[\"<|turn>\", \"<turn|>\"]}"
WRONG_MARKERS="${PROVE_WRONG_MARKERS:-[\"<start_of_turn>\", \"<end_of_turn>\"]}"
STOP_SEQUENCES="${PROVE_STOP_SEQUENCES:-[\"<turn|>\"]}"
DEVICE="${PROVE_DEVICE:-$(xcrun simctl list devices booted -j | python3 -c 'import json,sys; d=json.load(sys.stdin)["devices"]; print(next(x["udid"] for v in d.values() for x in v))')}"
APP_ID="app.chatterang.inference"
DD="$ROOT/.cache/dd"
LOG="$ROOT/.cache/prove-ios.log"

[ -f "$MODEL" ] || { echo "no such model: $MODEL" >&2; exit 2; }
echo "device : $DEVICE"
echo "model  : $MODEL ($(du -h "$MODEL" | cut -f1))"

cd "$ROOT"
npm run build:web >/dev/null

# The config the harness reads, and the harness itself, appended to the built
# index. Both land in dist/ only.
python3 - "$MODEL" "$PROMPT" "$WRONG_PROMPT" "$CREATIVE_PROMPT" \
         "$TEMPLATE_NAME" "$TEMPLATE_MARKERS" "$WRONG_MARKERS" "$STOP_SEQUENCES" <<'PY'
import json, pathlib, shutil, sys
root = pathlib.Path.cwd()
dist = root / 'dist'
shutil.copy(root / 'native/plugin-llama-cpp/tools/prove-ios.js', dist / 'prove-ios.js')
index = dist / 'index.html'
html = index.read_text()
cfg = json.dumps({
    'modelPath': sys.argv[1],
    'prompt': sys.argv[2],
    'wrongPrompt': sys.argv[3],
    'creativePrompt': sys.argv[4],
    'templateName': sys.argv[5],
    'templateMarkers': json.loads(sys.argv[6]),
    'wrongMarkers': json.loads(sys.argv[7]),
    'stopSequences': json.loads(sys.argv[8]),
    'contextLength': 1024,
    'maxTokens': 24,
})
html = html.replace('</body>', f'<script>window.__PROVE__={cfg};</script><script src="/prove-ios.js"></script></body>')
index.write_text(html)
PY

npx cap sync ios >/dev/null

xcodebuild -project ios/App/App.xcodeproj -scheme App -configuration Debug \
  -destination "platform=iOS Simulator,id=$DEVICE" -derivedDataPath "$DD" build >/dev/null
APP="$DD/Build/Products/Debug-iphonesimulator/App.app"

xcrun simctl terminate "$DEVICE" "$APP_ID" 2>/dev/null || true
xcrun simctl install "$DEVICE" "$APP"

echo "--- running (this takes as long as the model needs) ---"
# `--console-pty` streams the app's stdout, which is where the WebView's
# console.log lands. A timeout so a hang is a failure rather than a wait.
set +e
xcrun simctl launch --console-pty --terminate-running-process "$DEVICE" "$APP_ID" > "$LOG" 2>&1 &
LAUNCH_PID=$!
for _ in $(seq 1 "${PROVE_TIMEOUT_TICKS:-180}"); do
  grep -q '"step":"done"' "$LOG" && break
  sleep 5
done
kill "$LAUNCH_PID" 2>/dev/null
xcrun simctl terminate "$DEVICE" "$APP_ID" 2>/dev/null
set -e

echo "--- [PROVE] lines (full log: $LOG) ---"
grep -o '\[PROVE\] .*' "$LOG" | sed 's/^\[PROVE\] //' || true

python3 - "$LOG" <<'PY'
import json, re, sys
lines = []
for raw in open(sys.argv[1], errors='replace'):
    m = re.search(r'\[PROVE\] (\{.*\})\s*$', raw)
    if m:
        try: lines.append(json.loads(m.group(1)))
        except json.JSONDecodeError: pass

problems = []
if not any(l['step'] == 'done' for l in lines):
    problems.append('the harness never reached "done"')
for l in lines:
    if l.get('ok') is False:
        problems.append(f"step {l['step']}: {l.get('error')}")
    if 'llamaEndCount' in l and l['llamaEndCount'] != 1:
        problems.append(f"step {l['step']}: {l['llamaEndCount']} llamaEnd events, expected exactly 1")
    for counts in ([l['llamaEndCounts']] if 'llamaEndCounts' in l else []):
        if any(c != 1 for c in counts):
            problems.append(f"step {l['step']}: llamaEnd counts {counts}, expected all 1")

print()
if problems:
    print('FAILED:')
    for p in problems: print('  -', p)
    sys.exit(1)
print(f'OK: {len(lines)} steps, every generate emitted exactly one llamaEnd')
PY
