#!/usr/bin/env bash
#
# Drive `prove-android.js` on a connected device or emulator and print what it
# measured.
#
#   ./native/plugin-llama-cpp/tools/prove-android.sh [/abs/path/to/model.gguf]
#
# Builds the web app, appends the harness to the built `dist/index.html`,
# `cap sync`s, assembles the debug APK, installs it, launches it with logcat
# attached, and pulls the `[PROVE]` lines out of a log that is otherwise full
# of system noise.
#
# With no model argument the harness runs in refusal mode, which is the right
# mode when there is no `.so` for the device's ABI: it asserts that every
# method rejects readably and — the measurement that actually matters — that
# the app is still running afterwards.
#
# The harness touches only `dist/`, which is gitignored and regenerated by
# `npm run build:web`, so nothing it does survives into a normal build.
#
# Exit status is non-zero if any step reported `ok: false`, if the run never
# reached `done`, if any generate emitted other than exactly one `llamaEnd`,
# if logcat carried a FATAL EXCEPTION from our process, or if the app is no
# longer running when the harness finishes.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
MODEL="${1:-}"

# Only Android Studio's bundled JBR 21 works here: Temurin 26 fails Gradle with
# "Unsupported class file major version 70", and JDK 17 fails because Capacitor
# pins `sourceCompatibility 21`.
export JAVA_HOME="${JAVA_HOME:-/Applications/Android Studio.app/Contents/jbr/Contents/Home}"
SDK="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
ADB="$SDK/platform-tools/adb"
APP_ID="app.chatterang.inference"
LOG="$ROOT/.cache/prove-android.log"

# The turn markers the reference model actually uses, read out of its own GGUF
# chat template. WRONG_PROMPT is a different family's pair, kept deliberately
# so one run shows both and the difference is visible.
PROMPT="${PROVE_PROMPT:-<|turn>user
What is the capital city of Australia? Answer in one word.<turn|>
<|turn>model
}"
CREATIVE_PROMPT="<|turn>user
Invent one strange sentence about the sea. Just the sentence.<turn|>
<|turn>model
"
WRONG_PROMPT="<start_of_turn>user
What is the capital city of Australia? Answer in one word.<end_of_turn>
<start_of_turn>model
"

command -v "$ADB" >/dev/null 2>&1 || { echo "no adb at $ADB" >&2; exit 2; }
[ -z "$MODEL" ] || [ -f "$MODEL" ] || { echo "no such model: $MODEL" >&2; exit 2; }
DEVICE="${PROVE_DEVICE:-$("$ADB" devices | awk 'NR>1 && $2=="device" {print $1; exit}')}"
[ -n "$DEVICE" ] || { echo "no device: start an emulator or plug a phone in" >&2; exit 2; }

echo "device : $DEVICE ($("$ADB" -s "$DEVICE" shell getprop ro.product.cpu.abi | tr -d '\r'))"
if [ -n "$MODEL" ]; then
  echo "model  : $MODEL"
else
  echo "model  : (none — refusal mode)"
fi

mkdir -p "$ROOT/.cache"
cd "$ROOT"

# -- The reference the device is diffed against ---------------------------
#
# Token ids the SAME GGUF produces through node-llama-cpp on this host: the
# identical call `packages/inference-node/src/llama-cpp.ts:708` makes for the
# contract's `tokenize`,
#
#     return { tokens: this.#require(handle).model.tokenize(text, true) };
#
# where `true` is `parse_special`. That argument is the whole point: with
# `false` a control marker comes back as a handful of ordinary text tokens.
# iOS shipped exactly that bug and it was invisible until someone diffed the
# ids. Computing the reference here rather than pasting numbers in means the
# diff cannot go stale.
REFERENCE='{}'
if [ -n "$MODEL" ]; then
  echo "--- tokenizing the reference strings on this host ---"
  REFERENCE="$(node - "$MODEL" 2>/dev/null <<'JS' | tail -1
import { getLlama } from 'node-llama-cpp';
const llama = await getLlama();
const model = await llama.loadModel({ modelPath: process.argv[2] });
const strings = ['The capital of Australia is', 'hello world', 'Canberra', 'héllo 🌊 漢字'];
const out = {};
for (const s of strings) out[s] = Array.from(model.tokenize(s, true));
console.log(JSON.stringify(out));
JS
)"
  [ -n "$REFERENCE" ] || REFERENCE='{}'
  echo "reference: $REFERENCE"
fi

# -- The model, on the device ---------------------------------------------
#
# The app's own external files directory: readable by the app with no runtime
# permission, and writable by adb. `/data/local/tmp` is not -- SELinux labels
# it `shell_data_file` and an untrusted app cannot read it.
DEVICE_MODEL=""
if [ -n "$MODEL" ]; then
  DEVICE_DIR="/sdcard/Android/data/${APP_ID}/files"
  DEVICE_MODEL="${DEVICE_DIR}/$(basename "$MODEL")"
  "$ADB" -s "$DEVICE" shell mkdir -p "$DEVICE_DIR" >/dev/null 2>&1 || true
  # `|| true`: `set -o pipefail` is on, and a missing file makes the remote
  # `stat` — and so the whole pipeline — exit non-zero. Not finding the model
  # on the device is the normal first-run case, not an error.
  ON_DEVICE_SIZE="$("$ADB" -s "$DEVICE" shell "stat -c %s '$DEVICE_MODEL' 2>/dev/null" | tr -d '\r' || true)"
  if [ "$ON_DEVICE_SIZE" = "$(stat -f %z "$MODEL")" ]; then
    echo "model already on device at $DEVICE_MODEL"
  else
    echo "--- pushing $(du -h "$MODEL" | cut -f1) to $DEVICE_MODEL ---"
    "$ADB" -s "$DEVICE" push "$MODEL" "$DEVICE_MODEL" >/dev/null
  fi
fi

npm run build:web >/dev/null

# The config the harness reads, and the harness itself, appended to the built
# index. Both land in dist/ only.
python3 - "$DEVICE_MODEL" "$PROMPT" "$WRONG_PROMPT" "$CREATIVE_PROMPT" "$REFERENCE" <<'PY'
import json, pathlib, shutil, sys
root = pathlib.Path.cwd()
dist = root / 'dist'
shutil.copy(root / 'native/plugin-llama-cpp/tools/prove-android.js', dist / 'prove-android.js')
index = dist / 'index.html'
html = index.read_text()
cfg = {
    'prompt': sys.argv[2],
    'wrongPrompt': sys.argv[3],
    'creativePrompt': sys.argv[4],
    'templateName': 'gemma4',
    'templateMarkers': ['<|turn>', '<turn|>'],
    'wrongMarkers': ['<start_of_turn>', '<end_of_turn>'],
    'stopSequences': ['<turn|>'],
    'contextLength': 1024,
    'maxTokens': 24,
}
cfg['tokenizerReference'] = json.loads(sys.argv[5])
if sys.argv[1]:
    cfg['modelPath'] = sys.argv[1]
html = html.replace(
    '</body>',
    f'<script>window.__PROVE__={json.dumps(cfg)};</script><script src="/prove-android.js"></script></body>',
)
index.write_text(html)
PY

npx cap sync android >/dev/null
( cd "$ROOT/android" && ./gradlew --quiet :app:assembleDebug )
APK="$ROOT/android/app/build/outputs/apk/debug/app-debug.apk"
[ -f "$APK" ] || { echo "no APK at $APK" >&2; exit 2; }

"$ADB" -s "$DEVICE" shell am force-stop "$APP_ID" >/dev/null 2>&1 || true
"$ADB" -s "$DEVICE" install -r "$APK" >/dev/null
"$ADB" -s "$DEVICE" logcat -c || true

echo "--- running (this takes as long as the model needs) ---"
"$ADB" -s "$DEVICE" logcat > "$LOG" 2>&1 &
LOGCAT_PID=$!
"$ADB" -s "$DEVICE" shell monkey -p "$APP_ID" -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1

set +e
for _ in $(seq 1 "${PROVE_TIMEOUT_TICKS:-180}"); do
  grep -q '"step":"done"' "$LOG" && break
  grep -q 'FATAL EXCEPTION' "$LOG" && break
  sleep 5
done
# Whether the process is still alive is the whole point of the refusal proof.
PID="$("$ADB" -s "$DEVICE" shell pidof "$APP_ID" | tr -d '\r')"
kill "$LOGCAT_PID" 2>/dev/null
set -e

echo "--- [PROVE] lines (full log: $LOG) ---"
grep -o '\[PROVE\] .*' "$LOG" | sed 's/^\[PROVE\] //' || true

if grep -q 'FATAL EXCEPTION' "$LOG"; then
  echo "--- FATAL EXCEPTION in the log ---"
  grep -A 20 'FATAL EXCEPTION' "$LOG" | head -30
fi

ALIVE=0
[ -n "$PID" ] && ALIVE=1
echo "--- app still running afterwards: $ALIVE (pid '${PID:-none}') ---"

python3 - "$LOG" "$ALIVE" <<'PY'
import json, re, sys

lines = []
fatal = False
for raw in open(sys.argv[1], errors='replace'):
    if 'FATAL EXCEPTION' in raw:
        fatal = True
    m = re.search(r'\[PROVE\] (\{.*\})\s*$', raw)
    if m:
        try:
            lines.append(json.loads(m.group(1)))
        except json.JSONDecodeError:
            pass

problems = []
if fatal:
    problems.append('the log carried a FATAL EXCEPTION')
if sys.argv[2] != '1':
    problems.append('the app was not running when the harness finished')
if not any(l.get('step') == 'done' for l in lines):
    problems.append('the harness never reached "done"')
for l in lines:
    if l.get('ok') is False:
        problems.append(f"step {l['step']}: {l.get('error')}")
    if 'llamaEndCount' in l and l['llamaEndCount'] != 1:
        problems.append(f"step {l['step']}: {l['llamaEndCount']} llamaEnd events, expected exactly 1")
    for counts in ([l['llamaEndCounts']] if 'llamaEndCounts' in l else []):
        if any(c != 1 for c in counts):
            problems.append(f"step {l['step']}: llamaEnd counts {counts}, expected all 1")

if problems:
    print('\n--- FAILED ---')
    for p in problems:
        print(f'  - {p}')
    sys.exit(1)
print('\n--- PASSED ---')
PY
