#
# Keep rules for the llama.cpp JNI surface.
#
# WHY THIS FILE IS IN THE MODULE AND NOT IN `/android/app`
#
# `build.gradle` declares it as `consumerProguardFiles`, which is the only
# placement that survives. The whole `/android` tree is generated by
# `npx cap add android` and gitignored, so a rule written into
# `android/app/proguard-rules.pro` is lost on the next `cap sync` and on every
# fresh clone. `consumerProguardFiles` ships these rules INSIDE the module's
# AAR, and R8 merges them into whatever app consumes it — the same mechanism
# `@capacitor/android` itself uses (capacitor/build.gradle:50).
#
# WHAT BREAKS WITHOUT IT
#
# R8 renames by static reachability. `llama-jni.cpp` resolves Java by NAME at
# runtime, which is invisible to that analysis:
#
#   FindClass("app/chatterang/llama/LlamaBridge$GenerateResult")   (:586)
#   FindClass("app/chatterang/llama/LlamaBridge$BenchmarkResult")  (:818)
#   GetMethodID(callback_class, "onToken", "(Ljava/lang/String;)Z") (:574)
#   GetMethodID(result_class, "<init>", "(Ljava/lang/String;IIILjava/lang/String;D)V")
#
# and every exported symbol embeds the class and method name it implements —
# `Java_app_chatterang_llama_LlamaBridge_generate` is only found because the
# class is still called `LlamaBridge` and the method is still called
# `generate`.
#
# The failure is not a build error. Everything compiles, `System.loadLibrary`
# succeeds, `getCapabilities` answers — and then `FindClass` returns null in
# `generate`, which returns nullptr, and the model produces nothing. The
# generated app sets `minifyEnabled false`, so nothing has ever exercised
# this; turning minification on for a release build is an ordinary step.
#
# `tests/native-registration.test.ts` fences the pairing between these rules
# and the names `llama-jni.cpp` actually looks up.

# The class name and the native method names are both baked into the exported
# C symbols. `includedescriptorclasses` because a native method's parameter
# and return types must keep the names the JNI declares them with.
-keepclasseswithmembernames,includedescriptorclasses class app.chatterang.llama.LlamaBridge {
    native <methods>;
}

# Constructed from C++ by name and constructor descriptor. `-keep` also stops
# R8 inlining or horizontally merging them away, which it would otherwise be
# free to do: nothing in Kotlin constructs either one.
-keep class app.chatterang.llama.LlamaBridge$GenerateResult {
    <init>(...);
    <fields>;
}

-keep class app.chatterang.llama.LlamaBridge$BenchmarkResult {
    <init>(...);
}

# `GetObjectClass` on the anonymous implementation, then `GetMethodID` for
# "onToken" — so the name has to survive on the interface, which is what pins
# it on every override.
-keep interface app.chatterang.llama.LlamaBridge$TokenCallback {
    boolean onToken(java.lang.String);
}
