#!/usr/bin/env node
/**
 * Re-apply native configuration that `cap sync` does not preserve.
 *
 * `/android/` and `/ios/` are gitignored (`.gitignore:7-8`) — they are
 * generated, and Capacitor rewrites parts of them on every sync. Anything
 * edited there by hand is lost the next time someone runs `npm run sync`, and
 * is invisible to CI and to every other machine. So a native setting that has
 * to hold is a script, not an edit.
 *
 * What this applies, and why (#126):
 *
 * The app's store is the WebView's IndexedDB — conversations, personas,
 * settings, and provider API keys, which `ProviderConnection.apiKey` holds as
 * plain text. Both platforms back that up to the vendor's cloud by default.
 * The `privacy` command tells the user their data is "stored here and nowhere
 * else", so either the sentence goes or the backup does. The backup goes.
 *
 * Android additionally excludes `<device-transfer>`: a phone-to-phone
 * migration would carry this device's identity to another handset, where
 * revoking the original would not revoke the copy.
 *
 * The transform functions are exported and pure so `tests/privacy-copy.test.ts`
 * can check them without a native project on disk, which CI does not have.
 *
 * Run by `npm run sync`. Safe and idempotent to run again.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const ANDROID_MANIFEST = 'android/app/src/main/AndroidManifest.xml';
export const ANDROID_DATA_EXTRACTION_RULES =
  'android/app/src/main/res/xml/data_extraction_rules.xml';
export const ANDROID_BACKUP_RULES = 'android/app/src/main/res/xml/backup_rules.xml';
export const IOS_APP_DELEGATE = 'ios/App/App/AppDelegate.swift';
export const IOS_INFO_PLIST = 'ios/App/App/Info.plist';

/**
 * THE CAMERA USAGE STRING, and it is a product decision rather than a label.
 *
 * iOS shows this sentence in an OS dialog at the exact moment a privacy-first
 * app asks for a camera, and an App Review reviewer reads it against the store
 * listing. Once shipped it is expensive to change: a new string is a new
 * review, and it is a user-visible edit to a privacy promise people already
 * accepted.
 *
 * IT DELIBERATELY DOES NOT SAY "only". #128 drafted "uses the camera ONLY to
 * scan a pairing code", which is the strongest sentence available and also a
 * permanent constraint — any later feature reaching the same capture surface
 * (document scan, a camera attachment, vision input) would make a shipped
 * promise false. The owner ruled for the wording below, which makes the
 * identical promise about the FRAMES — the half a test can actually pin — and
 * spends no optionality to do it.
 *
 * The second sentence has to be true, and is what #128 asks be proven rather
 * than asserted: frames never touch the blob store and never reach a model.
 */
export const CAMERA_USAGE_DESCRIPTION =
  'Chatterang uses the camera to scan a pairing code shown on your computer. ' +
  'Nothing the camera sees is stored or sent anywhere.';

/** Marks generated blocks so a re-run replaces rather than duplicates. */
const MARKER = 'chatterang:no-backup';
/** Its own marker: the camera block is a different feature with a different life. */
const MARKER_CAMERA = 'chatterang:camera';

export const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/patch-native.mjs (${MARKER}). Edit that, not this. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" path="." />
        <exclude domain="file" path="." />
        <exclude domain="database" path="." />
        <exclude domain="sharedpref" path="." />
        <exclude domain="external" path="." />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" path="." />
        <exclude domain="file" path="." />
        <exclude domain="database" path="." />
        <exclude domain="sharedpref" path="." />
        <exclude domain="external" path="." />
    </device-transfer>
</data-extraction-rules>
`;

export const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/patch-native.mjs (${MARKER}). Edit that, not this. -->
<full-backup-content>
    <exclude domain="root" path="." />
    <exclude domain="file" path="." />
    <exclude domain="database" path="." />
    <exclude domain="sharedpref" path="." />
    <exclude domain="external" path="." />
</full-backup-content>
`;

/**
 * Turn off Android's auto-backup and point at the rules files.
 *
 * Throws rather than returning the input unchanged if the attribute it expects
 * is absent: a silent no-op here reinstates the leak while every test that
 * reads this function's output still passes.
 */
export function patchAndroidManifest(xml) {
  if (/android:allowBackup="false"/.test(xml)) {
    return /android:dataExtractionRules=/.test(xml)
      ? xml
      : xml.replace(
          /(\s*)android:allowBackup="false"/,
          `$1android:allowBackup="false"$1android:dataExtractionRules="@xml/data_extraction_rules"$1android:fullBackupContent="@xml/backup_rules"`,
        );
  }
  if (!/android:allowBackup="true"/.test(xml)) {
    throw new Error(
      `${ANDROID_MANIFEST}: no android:allowBackup attribute to patch. Capacitor's ` +
        'template changed; update scripts/patch-native.mjs rather than editing the manifest.',
    );
  }
  return xml.replace(
    /(\s*)android:allowBackup="true"/,
    `$1android:allowBackup="false"$1android:dataExtractionRules="@xml/data_extraction_rules"$1android:fullBackupContent="@xml/backup_rules"`,
  );
}

/**
 * Declare the camera permission, and declare the hardware OPTIONAL.
 *
 * `<uses-feature android:required="false">` is not boilerplate here. Declaring
 * `CAMERA` without it makes Play treat a camera as a device requirement and
 * hide the app from hardware that has none. That would be wrong on the facts:
 * pairing has a typed route that needs no camera at all, so a camera-less
 * tablet is a device this app works on. The permission says "we may ask"; the
 * feature line says "you do not need one".
 */
export function patchAndroidCamera(xml) {
  if (/android\.permission\.CAMERA/.test(xml)) return xml;
  if (!/<manifest[\s>]/.test(xml)) {
    throw new Error(
      `${ANDROID_MANIFEST}: no <manifest> element to patch. Capacitor's template changed; ` +
        'update scripts/patch-native.mjs rather than editing the manifest.',
    );
  }
  const block =
    `\n\n    <!-- ${MARKER_CAMERA} — generated by scripts/patch-native.mjs. Edit that, not this. -->\n` +
    `    <uses-permission android:name="android.permission.CAMERA" />\n` +
    `    <uses-feature android:name="android.hardware.camera" android:required="false" />`;
  return xml.replace(/(<manifest\b[^>]*>)/, `$1${block}`);
}

/**
 * Add the camera usage string to the generated Info.plist.
 *
 * Measured, not assumed: without this key `navigator.mediaDevices` is not
 * merely permission-blocked in WKWebView, it is UNDEFINED — at
 * `capacitor://localhost` and at an `http://localhost` origin alike. #128
 * inferred the custom URL scheme was the cause; it is not, and `dev/probe-128/`
 * holds the two-origin experiment and its paired control. So this key is not a
 * label on a capability the app already has. It is the capability.
 */
export function patchInfoPlist(plist) {
  if (plist.includes('NSCameraUsageDescription')) return plist;
  if (!/<dict>/.test(plist)) {
    throw new Error(
      `${IOS_INFO_PLIST}: no <dict> to patch. Capacitor's template changed; update ` +
        'scripts/patch-native.mjs rather than editing the plist.',
    );
  }
  return plist.replace(
    /<dict>/,
    `<dict>\n\t<!-- ${MARKER_CAMERA} — generated by scripts/patch-native.mjs. Edit that, not this. -->\n` +
      `\t<key>NSCameraUsageDescription</key>\n\t<string>${CAMERA_USAGE_DESCRIPTION}</string>`,
  );
}

const SWIFT_BLOCK = `
    // ${MARKER} — generated by scripts/patch-native.mjs. Edit that, not this.
    //
    // The counterpart to android:allowBackup="false" (#126). Library/WebKit is
    // where WKWebView keeps IndexedDB, which is this app's whole store. iOS
    // backs the Library directory up to iCloud and iTunes by default, so
    // without this the privacy command's "stored here and nowhere else" is
    // false on iOS.
    //
    // A device identity key does not belong here at all when one exists: it
    // belongs in the Keychain under kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
    // which is not backed up and does not survive onto a restored device.
    private func excludeWebViewStorageFromBackup() {
        let fileManager = FileManager.default
        for library in fileManager.urls(for: .libraryDirectory, in: .userDomainMask) {
            let webKit = library.appendingPathComponent("WebKit", isDirectory: true)
            guard fileManager.fileExists(atPath: webKit.path) else { continue }

            var url = webKit
            var values = URLResourceValues()
            values.isExcludedFromBackup = true
            do {
                try url.setResourceValues(values)
            } catch {
                NSLog("chatterang: could not exclude %@ from backup: %@",
                      webKit.path, String(describing: error))
            }
        }
    }
`;

/**
 * Add the backup exclusion to the generated AppDelegate.
 *
 * Called from both `didFinishLaunchingWithOptions` and
 * `applicationDidBecomeActive`: `Library/WebKit` does not exist on a first
 * launch, because the WebView has not created it yet. Setting the flag is
 * idempotent, so the second call costs nothing.
 */
export function patchAppDelegate(swift) {
  if (swift.includes(MARKER)) return swift;

  const launch = `didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {`;
  const active = `func applicationDidBecomeActive(_ application: UIApplication) {`;
  if (!swift.includes(launch) || !swift.includes(active)) {
    throw new Error(
      `${IOS_APP_DELEGATE}: expected AppDelegate methods not found. Capacitor's template ` +
        'changed; update scripts/patch-native.mjs.',
    );
  }

  return swift
    .replace(launch, `${launch}\n        excludeWebViewStorageFromBackup()`)
    .replace(active, `${active}\n        excludeWebViewStorageFromBackup()`)
    .replace(/\n}\s*$/, `\n${SWIFT_BLOCK}}\n`);
}

function write(relative, contents) {
  const path = resolve(root, relative);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, 'utf8');
}

function patchFile(relative, transform) {
  const path = resolve(root, relative);
  if (!existsSync(path)) return false;
  const before = readFileSync(path, 'utf8');
  const after = transform(before);
  if (after !== before) writeFileSync(path, after, 'utf8');
  return true;
}

/**
 * WHAT `main` APPLIES, AS DATA RATHER THAN AS CODE.
 *
 * A pure transform that nobody calls is the failure this repo keeps finding:
 * a guard whose output nothing reads (#259), a sentence that outlived its
 * code. Every transform here is exported and separately tested, which proves
 * each one WORKS and proves nothing about whether it RUNS. Listing the wiring
 * makes that testable too — `tests/privacy-copy.test.ts` asserts the Info.plist
 * patch is in this list, so deleting the call fails a test rather than quietly
 * shipping an iOS build where `getUserMedia` is undefined.
 *
 * The Android manifest is composed rather than merged into one transform:
 * backup and camera are two features with two reasons, and each is checked
 * alone.
 */
export const NATIVE_PATCHES = [
  {
    platform: 'android',
    file: ANDROID_MANIFEST,
    transform: (xml) => patchAndroidCamera(patchAndroidManifest(xml)),
  },
  { platform: 'ios', file: IOS_APP_DELEGATE, transform: patchAppDelegate },
  { platform: 'ios', file: IOS_INFO_PLIST, transform: patchInfoPlist },
];

function main() {
  const done = [];

  if (existsSync(resolve(root, 'android'))) {
    write(ANDROID_DATA_EXTRACTION_RULES, DATA_EXTRACTION_RULES_XML);
    done.push('android');
  }

  if (existsSync(resolve(root, 'ios'))) {
    done.push('ios');
  }

  for (const patch of NATIVE_PATCHES) {
    if (done.includes(patch.platform)) patchFile(patch.file, patch.transform);
  }

  // Not an error: a web-only or CI checkout has neither platform added, and
  // `cap sync` is what creates them.
  console.log(
    done.length
      ? `patch-native: applied backup exclusions and camera permission to ${done.join(', ')}`
      : 'patch-native: no native platforms present, nothing to do',
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main();
}
